<?php

declare(strict_types=1);

namespace Studiometa\Foehn\PageCache\ServerConfig;

use Studiometa\Foehn\Config\PageCacheConfig;

/**
 * The nginx configuration that serves a stored page without starting PHP at all.
 *
 * Generated, never hand-written, because it bakes in policy only the loaded config
 * knows — which cookies bypass, which query args are ignored — and because `if` inside
 * `location` is sharp enough that a half-edited copy is a real hazard.
 *
 * Three things about the shape are worth knowing before editing this class.
 *
 * **The rules are server-level, not wrapped in a `location`.** A flag is decided by a
 * sequence of `set`/`if` in the server rewrite phase, and one `rewrite … last` sends the
 * request at the stored file. This is the shape of the `prod-wp-rocket.conf` that
 * `studiometa/wordpress-project` has run in ddev and in production for years, and it is
 * what makes the include compose: it declares no `location /`, so nothing has to be
 * removed from the site's own configuration and misses fall through to whatever front
 * controller block is already there.
 *
 * **`set` inside `if` is why it has to be server-level.** Building a canonical filename
 * from the keyed query args needs `set`, and inside a `location` a matched `if` continues
 * in an implicit location that inherits no content handler — a `try_files` there is
 * silently skipped, so every request carrying `?utm_source=` falls through to PHP while
 * still looking like it worked. That was a real bug in this file's first version. At
 * server level, `set` under `if` is the documented behaviour of the rewrite module rather
 * than the trap it is in a location.
 *
 * **The stored files are unreachable from outside.** They are served through an internal
 * redirect into a `location ^~` marked `internal`, so no visitor can request a cache file
 * by name, and a `.php` written under that directory by any cache is unreachable as well
 * as unexecutable.
 *
 * What it cannot do: enforce a TTL. nginx has no way to look at a file's age, which is why
 * {@see \Studiometa\Foehn\PageCache\Sweeper} is in v1 rather than deferred.
 */
final readonly class NginxSnippet
{
    private SnippetPolicy $policy;

    public function __construct(PageCacheConfig $config)
    {
        $this->policy = new SnippetPolicy($config);
    }

    /**
     * The snippet, or null when the configured cache path is not under the document root.
     */
    public function render(): ?string
    {
        $cache = $this->policy->cacheUrlPath();

        if ($cache === null) {
            return null;
        }

        $cookies = $this->policy->cookiePattern();
        $args = $this->policy->knownQueryPattern();
        $maxAge = max(0, $this->policy->config->browserMaxAge);
        $hash = $this->policy->hash();
        $cacheRoot = dirname($cache);
        $maintenance = $this->policy->maintenanceUrlPath();
        $canonical = $this->statements(
            $this->policy->canonicalQueryStatements(),
            'No keyed query args are configured (PageCacheConfig::$cacheQueryArgs).',
        );
        $repeated = $this->statements(
            $this->policy->repeatedQueryStatements(),
            'No keyed query args, so none can be repeated.',
        );

        return <<<NGINX
            # Foehn page cache — generated by `wp foehn cache:config --server=nginx`.
            # DO NOT EDIT. Regenerate after changing app/page-cache*.config.php.
            # policy: {$hash}
            #
            # Include this inside your `server { }` block. It composes with a stock
            # WordPress `location /` — nothing has to be removed.

            set \$foehn_bypass 1;

            # The keyed query args, in the configuration's canonical order.
            set \$foehn_q "";
            {$canonical}
            set \$foehn_variant "";
            if (\$foehn_q != "") {
                set \$foehn_variant "__\$foehn_q";
            }

            # `\$uri` interpolated whole, never through a regex capture. `\$uri` itself is
            # decoded, which is what makes an accented permalink resolve to the file PHP
            # wrote — but `\$1` from `if (\$uri ~ …)` comes back percent-encoded, so deriving
            # the path that way looked correct and quietly missed every non-ASCII URL. Two
            # candidates instead of one capture: WordPress may or may not put a trailing
            # slash on a permalink, and /foo and /foo/ are one page and one file.
            set \$foehn_url "{$cache}/\$host\${uri}index\$foehn_variant.html";

            if (!-f "\$document_root\$foehn_url") {
                set \$foehn_url "{$cache}/\$host\${uri}/index\$foehn_variant.html";
            }
            if (!-f "\$document_root\$foehn_url") {
                set \$foehn_bypass 0;
            }
            if (\$request_method != GET) {
                set \$foehn_bypass 0;
            }
            # Every arg must be one this cache was told about — ignored or keyed. Order
            # does not enter into it; anything unknown is PHP's decision to make.
            if (\$args !~ "{$args}") {
                set \$foehn_bypass 0;
            }
            {$repeated}
            if (\$http_cookie ~* "({$cookies})") {
                set \$foehn_bypass 0;
            }
            if (-f "\$document_root{$maintenance}") {
                set \$foehn_bypass 0;
            }

            if (\$foehn_bypass = 1) {
                rewrite ^ "\$foehn_url" last;
            }

            # Nothing under the cache directory is reachable from outside. `^~` beats every
            # regex location, including the FastCGI one, so a .php file written there by
            # any cache is unreachable as well as unexecutable, and `internal` means only
            # the rewrite above can get in.
            #
            # The headers live here rather than at server level so that a miss carries no
            # header from nginx at all: PHP emits its own MISS or BYPASS with a reason, and
            # two writers of one header name produce a response with both.
            location ^~ {$cacheRoot}/ {
                internal;
                etag on;
                add_header X-Foehn-Cache HIT;
                add_header X-Foehn-Cache-Via nginx;
                add_header Cache-Control "public, max-age={$maxAge}, must-revalidate";
                add_header Vary "Cookie, Accept-Encoding";
            }
            NGINX;
    }

    /**
     * The `# policy:` line a generated snippet carries, for comparing against a file.
     */
    public function hash(): string
    {
        return $this->policy->hash();
    }

    /**
     * Generated statements, or a comment saying why there are none.
     *
     * No indentation is added: a flexible heredoc strips its closing marker's indentation
     * from the literal text at compile time, so an interpolated value lands at column
     * zero, which is where the rest of these server-level statements sit. A blank line
     * here would survive into the file and read as a mistake.
     */
    private function statements(string $statements, string $whenEmpty): string
    {
        return $statements === '' ? '# ' . $whenEmpty : $statements;
    }
}
