<?php

declare(strict_types=1);

namespace Studiometa\Foehn\PageCache\ServerConfig;

use Studiometa\Foehn\Config\PageCacheConfig;

/**
 * The nginx configuration that serves a stored page without starting PHP at all.
 *
 * Generated, never hand-written, because it bakes in policy only the loaded config
 * knows — which cookies bypass, which query args are ignored — and because `if` inside
 * `location` is sharp enough that a half-edited copy is a real hazard.
 *
 * Two things about the shape are worth knowing before editing this class.
 *
 * **It is an include, not a replacement.** The spec called for replacing the site's
 * `location /`, which would have meant taking over ddev's generated `nginx-site.conf`
 * and losing its future updates. A regex location does the same job while composing:
 * nginx tests regex locations before falling back to the longest prefix match, so
 * `location ~ …` wins over a stock `location /` without the two ever colliding. The
 * include therefore drops into `server{}` next to whatever is already there.
 *
 * **The catch-all excludes `.php` in its own pattern** rather than relying on being
 * placed after the FastCGI location. Regex locations are tried in the order they appear,
 * so an include placed too early would otherwise swallow `/index.php` and take the site
 * down. A guard in the pattern makes the ordering a performance question instead of a
 * correctness one.
 *
 * What it cannot do: enforce a TTL. `try_files` has no way to look at a file's age, which
 * is why {@see \Studiometa\Foehn\PageCache\Sweeper} is in v1 rather than deferred.
 */
final readonly class NginxSnippet
{
    private SnippetPolicy $policy;

    public function __construct(PageCacheConfig $config)
    {
        $this->policy = new SnippetPolicy($config);
    }

    /**
     * The snippet, or null when the configured cache path is not under the document root.
     */
    public function render(): ?string
    {
        $cache = $this->policy->cacheUrlPath();

        if ($cache === null) {
            return null;
        }

        $cookies = $this->policy->cookiePattern();
        $args = $this->policy->ignorableQueryPattern();
        $maxAge = max(0, $this->policy->config->browserMaxAge);
        $hash = $this->policy->hash();
        $cacheRoot = dirname($cache);

        return <<<NGINX
            # Foehn page cache — generated by `wp foehn cache:config --server=nginx`.
            # DO NOT EDIT. Regenerate after changing app/page-cache*.config.php.
            # policy: {$hash}
            #
            # Include this inside your `server { }` block. It composes with a stock
            # WordPress `location /` — nothing has to be removed.

            # Nothing under the cache directory is reachable from outside. `^~` beats every
            # regex location, including the FastCGI one, so a .php file written there by
            # any cache is unreachable as well as unexecutable.
            location ^~ {$cacheRoot}/ {
                internal;
            }

            # The `.php` guard is in the pattern so this include is safe to place anywhere
            # in the server block.
            location ~ "^(?!.*\\.php\$)" {
                error_page 418 = @foehn_miss;
                recursive_error_pages on;
                absolute_redirect off;

                # Every `if` here contains nothing but `return`, which is the only form
                # nginx documents as safe inside a location. A `set` would look tidier and
                # would silently break the `try_files` below: when an `if` matches, the
                # request continues in an implicit location that does not inherit it, so
                # every cacheable request carrying `?utm_source=` would fall through to
                # PHP while still looking like it worked.
                if (\$request_method != GET) {
                    return 418;
                }
                # A query string made only of ignored args is the same page as no query at
                # all, in whatever order the args arrive. Anything else is a bypass.
                if (\$args !~ "{$args}") {
                    return 418;
                }
                if (\$http_cookie ~* "({$cookies})") {
                    return 418;
                }
                if (-f "\$document_root/.maintenance") {
                    return 418;
                }

                # Only reached when try_files below found a stored page: a fall-through to
                # @foehn_miss is an internal redirect, and these do not follow it.
                add_header X-Foehn-Cache HIT;
                add_header X-Foehn-Cache-Via nginx;
                add_header Cache-Control "public, max-age={$maxAge}, must-revalidate";
                add_header Vary "Cookie, Accept-Encoding";

                # Two candidates, because nginx cannot normalise a trailing slash the way
                # PHP does: /foo and /foo/ are one page and one file.
                try_files "{$cache}/\$host\${uri}index.html"
                          "{$cache}/\$host\${uri}/index.html"
                          @foehn_miss;
            }

            location @foehn_miss {
                try_files \$uri \$uri/ /index.php\$is_args\$args;
            }
            NGINX;
    }

    /**
     * The `# policy:` line a generated snippet carries, for comparing against a file.
     */
    public function hash(): string
    {
        return $this->policy->hash();
    }
}
