<?php

declare(strict_types=1);

namespace Studiometa\Foehn\Blocks;

use Studiometa\Foehn\Config\FoehnConfig;
use Studiometa\Foehn\Discovery\BlockDiscovery;
use Studiometa\Foehn\Discovery\DiscoveryRunner;

/**
 * Ships the generic block editor registrar and the discovered block definitions
 * to the block editor.
 *
 * Two artifacts with two different lifecycles:
 *
 * 1. The registrar is static. It only changes when Foehn changes, so it is a
 *    real file in the package that the installer copies into the web root on
 *    `composer install`. `vendor/` sits outside the document root and cannot be
 *    served to a browser.
 * 2. The block definitions are dynamic. They change whenever a developer adds
 *    or edits a block, so they come from discovery and are inlined before the
 *    registrar runs.
 */
final readonly class BlockEditorAssets
{
    /** Script handle shared by the registrar and its inline definitions. */
    public const string HANDLE = 'foehn-editor';

    /** Path of the generated registrar, relative to the WordPress content directory. */
    private const string SCRIPT_PATH = 'foehn/editor.js';

    /**
     * WordPress script handles the registrar reads its globals from.
     *
     * The registrar has a fixed, known import set, so this list is static on
     * purpose: there is nothing to extract and no second bundler is needed.
     *
     * @var list<string>
     */
    private const array DEPENDENCIES = [
        'wp-blocks',
        'wp-element',
        'wp-block-editor',
        'wp-components',
        'wp-server-side-render',
    ];

    public function __construct(
        private DiscoveryRunner $runner,
        private FoehnConfig $config,
    ) {}

    /**
     * Enqueue the registrar with the block definitions inlined before it.
     *
     * Handler for the `enqueue_block_editor_assets` action.
     */
    public function enqueue(): void
    {
        $definitions = $this->getDefinitions();

        if ($definitions === []) {
            return;
        }

        $path = $this->getScriptPath();

        if (!is_file($path)) {
            $this->reportMissingScript($path);

            return;
        }

        wp_enqueue_script(
            self::HANDLE,
            content_url(self::SCRIPT_PATH),
            self::DEPENDENCIES,
            // The file modification time, not the package version: in development
            // the package version is `dev-*` and would never bust the browser cache.
            (string) filemtime($path),
            true,
        );

        $json = wp_json_encode($definitions);

        if ($json === false) {
            return;
        }

        wp_add_inline_script(self::HANDLE, 'window.foehnBlocks = ' . $json . ';', 'before');
    }

    /**
     * Get the editor definitions of every discovered block.
     *
     * BlockDiscovery is not a container singleton, so resolving it from the
     * container would hand back a fresh, empty instance. The DiscoveryRunner is
     * the singleton that owns the populated discovery instances.
     *
     * @return list<array<string, mixed>>
     */
    private function getDefinitions(): array
    {
        $discovery = $this->runner->getDiscoveries()[BlockDiscovery::class] ?? null;

        if (!$discovery instanceof BlockDiscovery) {
            return [];
        }

        return $discovery->getEditorDefinitions();
    }

    /**
     * Get the absolute path of the generated registrar.
     */
    private function getScriptPath(): string
    {
        return constant('WP_CONTENT_DIR') . '/' . self::SCRIPT_PATH;
    }

    /**
     * Report a missing registrar.
     *
     * Without the registrar no Foehn block is registered client-side, so every one of
     * them disappears from the inserter and existing ones render as unsupported. That
     * is a total failure, and it must not depend on debug mode to be visible: the
     * message is always printed to the console of the editor screen where the symptom
     * shows up. `wp-blocks` is always enqueued there, and it carries the message even
     * though the registrar itself was never enqueued.
     */
    private function reportMissingScript(string $path): void
    {
        $message = sprintf(
            '[Foehn] Block editor registrar not found at "%s". It is generated by `composer install`. '
            . 'Until it exists, no Foehn block is available in the editor.',
            $path,
        );

        $encoded = wp_json_encode($message);

        if ($encoded !== false) {
            wp_add_inline_script('wp-blocks', 'window.console && window.console.error(' . $encoded . ');');
        }

        if ($this->config->isDebugEnabled()) {
            trigger_error($message, E_USER_WARNING);
        }
    }
}
